export const PAGINATION = {
  DEFAULT_PAGE_SIZE: 50,
  MAX_PAGE_SIZE: 200,
} as const;

export const FREE_TAGS_MAX = 20;

export const LIMITS = {
  ITEM_TITLE_MAX: 300,
  ITEM_BODY_MAX: 50_000,
  TAG_NAME_MAX: 100,
  TAGS_PER_ITEM_MAX: 20,
  DEPS_PER_ITEM_MAX: 50,
  DEP_CHAIN_DEPTH_MAX: 20,
  DASHBOARD_BLOCKS_MAX: 12,
  DASHBOARD_BLOCKS_MIN: 1,
  DASHBOARD_COLUMNS_DEFAULT: 3,
  IMPORT_FILE_SIZE_MAX: 10 * 1024 * 1024, // 10 MB
  IMPORT_BATCH_MAX: 500,
  BUG_REPORT_DESC_MAX: 5_000,
  BUG_REPORT_PAGE_MAX: 200,
  BUG_REPORT_UA_MAX: 500,
  CLIENT_ERROR_MSG_MAX: 2_000,
  CLIENT_ERROR_STACK_MAX: 8_000,
  CLIENT_ERROR_CONTEXT_MAX: 500,
  CLIENT_ERROR_UA_MAX: 500,
  CLIENT_ERROR_SHORT_MAX: 50,
} as const;
